name: Auto commit

on:
  schedule:
    - cron: '15 4,8,15 * * 0-2'
    - cron: '0 8-20 * * 1-5'
    - cron: '10 3-11 4-20 * *'

  workflow_dispatch:

jobs:
  auto_commit:
    name: 'Auto push a commit to my repo'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create sample file with just timestamp
        run: date +%s >> report.txt

      - name: Check for changes
        run: |
          git add report.txt
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

      - name: Commit and push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "Automated update profile"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
